# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cross-Compile Python Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable for ${{ matrix.os }}
      run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pyinstaller --onefile __main__.py -n hello_world
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            pyinstaller --onefile __main__.py -n hello_world
          fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hello-executable-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/hello_world

  build-macos:
    runs-on: macos-latest
    needs: build  # Ensure this job runs after the build job

    strategy:
      matrix:
        python-version: [3.12, 3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build Application for macOS
        run: |
          pyinstaller --onefile __main__.py -n hello_world  # Use --windowed for GUI apps

      - name: Upload macOS .app Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-app-macos-${{ matrix.python-version }}
          path: dist/hello_world
